modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="enteringyourmind"
version="1.0.0"
displayName="enteringyourmind"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="JY9146, MCreator"
description="A Minecraft mod where you enter your subconscious and fight your insecurities."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.enteringyourmind]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.enteringyourmind]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration